Document: robomongo
Title: Debian robomongo Manual
Author: <insert document author here>
Abstract: This manual describes what robomongo is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/robomongo/robomongo.sgml.gz

Format: postscript
Files: /usr/share/doc/robomongo/robomongo.ps.gz

Format: text
Files: /usr/share/doc/robomongo/robomongo.text.gz

Format: HTML
Index: /usr/share/doc/robomongo/html/index.html
Files: /usr/share/doc/robomongo/html/*.html
